# Generated by Django 3.2.8 on 2021-10-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(default='', max_length=256)),
                ('product_name', models.CharField(default='', max_length=256)),
                ('product_num', models.IntegerField(null=True)),
                ('categories', models.TextField(null=True)),
                ('img_src', models.CharField(default='', max_length=256)),
                ('price', models.CharField(default='', max_length=32)),
                ('review_len', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_value', models.FloatField(default=0, null=True)),
                ('pos_neg_rate', models.FloatField(default=0, null=True)),
                ('search_value', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=256)),
                ('score', models.FloatField(default=0, null=True)),
                ('keywords', models.CharField(max_length=256)),
                ('morph', models.CharField(default='', max_length=256)),
                ('xai_vale', models.CharField(default='', max_length=256)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.productmodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=20)),
                ('summarization', models.CharField(default='', max_length=256)),
                ('keyword_positive', models.FloatField(default=60)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.productmodel')),
            ],
            options={
                'db_table': 'PDkeyword',
            },
        ),
    ]
